```typescript
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps all pages.
 * Applies the Inter font and a dark background color.
 *
 * @param props - Component props.
 * @param props.children - The page content to render inside the layout.
 * @returns A JSX element containing the layout structure.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     
    <div className={`${inter.className} bg-gray-900 h-screen`}>
       
        {children}</div>
     
      
  
  );
}
```