```typescript
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component that wraps all pages in the application.
 * It applies the Inter font class and a dark background to the entire page.
 *
 * @param props - The component props.
 * @param props.children - The page content to render inside the layout.
 * @returns The root layout wrapper element.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     
    <div className={`${inter.className} bg-gray-900 h-screen`}>
       
        {children}</div>
     
      
  
  );
}
```