
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/appNavbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     
    <div className={`${inter.className} bg-gradient-to-r from-black via-slate-600 to-black flex h-screen`}>
    <Sidebar />
    
   
    
      {children}
    
  </div>
  
  
     
      
  
  );
}
