```typescript
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/appNavbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component serving as the top-level layout for the application.
 * It includes a sidebar and applies global styling with a gradient background.
 *
 * @param props.children - The main content to be rendered inside the layout.
 * @returns A JSX element representing the full-page layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     
    <div className={`${inter.className} bg-gradient-to-r from-black via-slate-600 to-black flex h-screen`}>
    <Sidebar />
    
   
    
      {children}
    
  </div>
  
  
     
      
  
  );
}
```