```typescript
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

/**
 * Metadata configuration for the root layout of the Next.js application.
 * This constant defines the default title and description for the application.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout component that serves as the main layout wrapper for the application.
 * It provides the global structure including the Navbar, main content area, and Footer.
 * The layout uses the Inter font and a dark background theme.
 *
 * @param props - The props object containing child components.
 * @param props.children - The React nodes to be rendered as the main content.
 * @returns A JSX element representing the root layout structure.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     
      <div className={`${inter.className} bg-gray-900 h-screen`}>
        <Navbar/>
        {children}
        <Footer/>
        </div>
     
      
  
  );
}
```