```typescript
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Root layout component for the Next.js application.
 * Provides a consistent page structure including the navigation bar, main content area, and footer.
 *
 * @param children - The page content to be rendered within the layout.
 * @returns The JSX structure representing the entire layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
     
      <div className={`${inter.className} bg-gray-900 h-screen`}>
        <Navbar/>
        {children}
        <Footer/>
        </div>
     
      
  
  );
}
```